# Values used for the deployed application.
replicaCount: 1

secondstack:
  enabled: "true"

service:
  name: upp-aggregate-healthcheck

env:
  PATH_PREFIX: "/__health"

categories:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels:
         healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: default
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.content-publish
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: content-publish
      category.services: upp-notifications-creator,notifications-push,cms-kafka-bridge-pub-pre-prod,cms-notifier,content-ingester,document-store-api,video-mapper,wordpress-article-mapper,wordpress-image-mapper
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.content-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: content-read
      category.services: api-policy-component,content-public-read,document-store-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.internalcontent-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: internalcontent-read
      category.services: api-policy-component,content-public-read,document-store-api,system-healthcheck,enriched-content-read-api,internal-content-api,public-annotations-api,relations-api
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.lists-publish
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: lists-publish
      category.services: cms-kafka-bridge-pub-pre-prod,cms-notifier,upp-list-validator,list-ingester,public-lists-api,public-concordances-api,public-things-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: read
      category.services: api-policy-component,concept-rw-elasticsearch,content-public-read,document-store-api,enriched-content-read-api,internal-content-api,public-lists-api,list-notifications-rw,notifications-rw,public-brands-api,public-concordances-api,public-content-by-concept-api,public-organisations-api,public-people-api,public-things-api
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.concordances-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: concordances-read
      category.services: api-policy-component,public-concordances-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.enrichedcontent-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: enrichedcontent-read
      category.services: api-policy-component,content-public-read,document-store-api,enriched-content-read-api,public-annotations-api,relations-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.image-publish
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: image-publish
      category.services: cms-kafka-bridge-pub-pre-prod,cms-notifier,content-ingester,document-store-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.lists-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: lists-read
      category.services: api-policy-component,public-lists-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.system
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: system
      category.services: system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.annotations-publish
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: annotations-publish
      category.services: public-annotations-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.annotations-read
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: annotations-read
      category.services: annotations-rw-neo4j,upp-next-video-annotations-mapper,pac-annotations-mapper,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.concept-search
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: concept-search
      category.services: concept-search-api,system-healthcheck
      category.refreshrate: "60"
      category.issticky: "false"
