# Values used for the deployed application.
replicaCount: 1

secondstack:
  enabled: "true"
service:
  name: upp-aggregate-healthcheck
env:
  PATH_PREFIX: "/__health"
categories:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: default
      category.refreshrate: "60"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.publish
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: publish
      category.services: cms-notifier, native-ingester-cms, cms-metadata-notifier, native-ingester-metadata, nativerw, draft-annotations-publisher
      category.refreshrate: "60"
      category.issticky: "true"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.publishing-monitors
      labels:
         healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: publishing-monitors
      category.services: >-
        publish-availability-monitor,
        cm-synthetic-audio-publication-monitor,
        cm-synthetic-article-publication-monitor,
        cm-synthetic-content-collection-pub-monitor,
        cm-synthetic-content-placeholder-pub-monitor,
        cm-synthetic-list-publication-monitor,
        cm-synthetic-live-blog-package-pub-monitor,
        cm-synthetic-live-blog-post-pub-monitor,
        cm-synthetic-graphic-publication-monitor,
        cm-synthetic-image-publication-monitor,
        cm-synthetic-imageset-publication-monitor,
        cm-synthetic-live-event-publication-monitor,
        cm-synthetic-page-publication-monitor
      category.refreshrate: "60"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.system
      labels:
         healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: system
      category.services: coreos-version-checker, system-healthcheck
      category.refreshrate: "60"
