# Values used for the deployed application.
replicaCount: 2

service:
  name: upp-aggregate-healthcheck
env:
  PATH_PREFIX: "/__health"
ingress:
  enabled: "true"
categories:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels:
         healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: default
      category.refreshrate: "60"
      category.issticky: "false"
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.annotations-curation
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    immutable: false
    data:
      category.name: annotations-curation
      category.services: >- 
        annotations-publisher,
        draft-annotations-api,
        generic-rw-aurora
      category.refreshrate: "60"
      category.issticky: "false"
