version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/upp-aggregate-healthcheck
    docker:
      - image: circleci/golang:1
    environment:
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
    steps:
      - checkout
      - run:
          name: Make go get work
          command: sudo chown -R circleci:circleci /go/src
      - run:
          name: External Dependencies
          command: |
            GO111MODULE=off go get -u github.com/mattn/goveralls
            GO111MODULE=off go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Go Build
          command: go build -mod=readonly -v
      - run:
          name: Run Tests
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}/golang
            mkdir -p ${CIRCLE_COVERAGE_REPORT}
            go test -mod=readonly -race -v | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
            go test -mod=readonly -race -cover -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out
      - run:
          name: Upload Coverage
          command: goveralls -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /upp-aggregate-healthcheck
    docker:
      - image: docker:1.12.6-git
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
