# Default values for upp-aggregate-healthcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
replicaCount: 1
image:
  repository: coco/upp-aggregate-healthcheck
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi
env:
  PATH_PREFIX: ""
ingress:
  enabled: "false"
categories:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: default
      category.refreshrate: "5"

