# Default values for upp-aggregate-healthcheck.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
replicaCount: 1
secondstack:
  enabled: "false"
image:
  repository: coco/upp-aggregate-healthcheck
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi
env:
  PATH_PREFIX: ""
ingress:
  enabled: "false"
categories:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: category.default
      labels:
        healthcheck-categories-for: aggregate-healthcheck
    data:
      category.name: default
      category.refreshrate: "60"
metrics:
  # where we expose the metrics for prometheus
  path: /metrics
  # how often prometheus will call the metrics path
  interval: 30s
  # the name of the prometheus instance, as defined in
  # content-k8s-prometheus\helm\content-k8s-prometheus\app-configs\monitoring-metrics_{env}.yaml
  prometheusInstance: monitoring-metrics
