##this is an example deployment.yaml that should be customized in order to meet the configuration for app k8s deployment

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
      containers: 
      - name: {{ .Values.service.name }} 
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: 
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: environment
        - name: CLUSTER_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: cluster.url
        - name: GRAPHITE_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: PATH_PREFIX
          value: {{ .Values.env.PATH_PREFIX }} 
        ports: 
        - containerPort: 8080 
        livenessProbe: 
          tcpSocket: 
            port: 8080 
          initialDelaySeconds: 30 
        resources: 
{{ toYaml .Values.resources | indent 12 }}

