{{ if eq .Values.ingress.enabled "true" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: upp-aggregate-healthcheck
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
# Allow PATH_PREFIX to be accessed. Like: "__health"
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && Path(`{{ .Values.env.PATH_PREFIX }}`)
      services:
      - kind: Service
        namespace: default
        name: upp-aggregate-healthcheck
        port: 8080
        passHostHeader: true
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
# Allow everything with "__pod" to be accessed WITHOUT basic auth. Like: "__pods-health" and "/__pod-individual-health"
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && PathPrefix(`{{ .Values.env.PATH_PREFIX }}/__pod{/(?!__).+}`)
      services:
      - kind: Service
        namespace: default
        name: upp-aggregate-healthcheck
        port: 8080
        passHostHeader: true
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
# Deny access WITHOUT basic auth to anything else
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && PathPrefix(`{{ .Values.env.PATH_PREFIX }}/{/(?!__).+}`)
      middlewares:
      - name: basic-auth
        namespace: default
      services:
      - kind: Service
        namespace: default
        name: upp-aggregate-healthcheck
        port: 8080
        passHostHeader: true
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
    - kind: Rule
      match: HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.upp.ft.com`) && Path(`/__gtg`)
      services:
      - kind: Service
        namespace: default
        name: upp-aggregate-healthcheck
        port: 8080
        passHostHeader: true
        responseForwarding:
          flushInterval: 100ms
        strategy: RoundRobin
{{ end }}
