{{ if eq .Values.ingress.enabled "true" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.service.name}}-operation-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.com/health-checks: "true"
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
    - host: "*.ft.com"
      http:
        paths:
        - path: ~ {{ .Values.env.PATH_PREFIX }}/(?!__).+
          backend:
            serviceName: {{.Values.service.name}}
            servicePort: 8080
    - host: "*.upp.ft.com"
      http:
        paths:
        - path: ~ {{ .Values.env.PATH_PREFIX }}/(?!__).+
          backend:
            serviceName: {{.Values.service.name}}
            servicePort: 8080
{{ end }}
