apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
spec:
  endpoints:
    - port: 8080
    - path: "/metrics"
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
