apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: {{ .Values.service.name }}
    prometheus: {{ .Values.metrics.prometheusInstance }}
  name: {{ .Values.service.name }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.interval }}
    path: {{ .Values.metrics.path }}
  jobLabel: component
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
---
{{ if eq .Values.secondstack.enabled "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: {{ .Values.service.name }}-second
    prometheus: {{ .Values.metrics.prometheusInstance }}
  name: {{ .Values.service.name }}-second
spec:
  endpoints:
  - interval: {{ .Values.metrics.interval }}
    path: {{ .Values.metrics.path }}
  jobLabel: component
  selector:
    matchLabels:
      app: {{ .Values.service.name }}-second
{{ end }}